Add unittesting framework to workflow

diff --git a/.github/workflows/stm32build.yml b/.github/workflows/stm32build.yml
--- a/.github/workflows/stm32build.yml
+++ b/.github/workflows/stm32build.yml
@@ -9,7 +9,6 @@ on:
     paths: ['STM32/**', '.github/workflows/stm32build.yml']
 
 jobs: 
-
   # JOB to run change detection
   changes:
     runs-on: ubuntu-latest
@@ -36,6 +35,40 @@ jobs:
           LightController: STM32/LightController/**
           OTP: STM32/OTP/**
           Temperature: STM32/Temperature/**
+  run_tests:
+    needs: changes
+    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
+    strategy:
+      matrix:
+        # Parse JSON array containing names of all filters matching any of changed files
+        package: ${{ fromJSON(needs.changes.outputs.packages) }}
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3   # gets file environment with submodule included for libraries
+      with:
+        submodules: 'true'
+    # Check whether the unittest folder exist in the modified project. If so, run unittests.
+    - name: Check if unittests exist
+      id: unittests_exists
+      run: |
+        if [ -d "${{ matrix.package }}/UnitTesting" ]; then
+          echo 'exist=1' >> $GITHUB_ENV
+        else
+          echo 'exist=0' >> $GITHUB_ENV
+        fi
+    # Build and run unittests. If the unittest fails the line number is output.
+    - name: Run unittests
+      if: env.exist == '1'
+      run: |
+        cd "${{ matrix.package }}/UnitTesting"
+        cmake CMakeLists.txt
+        make
+        output=$(./CA_UnitTesting)
+        echo $output
+        if [[ $output =~ "failed" ]]; then 
+          echo "Test failed"
+          exit 1
+        fi
   build:
     needs: changes
     permissions:
